{{- $isSecretName := and (typeIs "map[string]interface {}" .Values.existingSecret)
          (get .Values.existingSecret "name") -}}
{{- $isPasswordExplicit := (typeIs "string" .Values.existingSecret) }}
apiVersion: v1
data:
  isSecretName: {{ $isSecretName | quote }}
  isPasswordExplicit: {{ $isPasswordExplicit | quote }}
  nameOfSecret: {{ include "null_checking_bug.evaluateNameOfSecret" . }}
  {{- if $isSecretName }}
  nameOfSecretFromValuesYaml: {{ .Values.existingSecret.name }}
  {{- end }}
  typeOfSecretName: {{ typeOf $isSecretName | quote }}
kind: Secret
metadata:
  name: jesse-frustration
  namespace: default
type: Opaque
