apiVersion: v1
data:
  isSecretName: {{ (include "null_checking_bug.isSecretName" .) | quote }}
  isPasswordExplicit: {{ (include "null_checking_bug.isPasswordExplicit" .) | quote }}
  nameOfSecret: {{ include "null_checking_bug.evaluateNameOfSecret" . }}
  {{- if (include "null_checking_bug.isSecretName" .) -}}
  nameOfSecretFromValuesYaml: {{ .Values.existingSecret.name }}
  {{- end }}
  typeOfSecretName: {{ typeOf (include "null_checking_bug.isSecretName" .) | quote }}
kind: Secret
metadata:
  name: jesse-frustration
  namespace: default
type: Opaque
